### ISSUE TITLE
Model structure

### ISSUE THREAD

**Issue by xman236** [baudm/VoxelNet-Keras#2]
Hi @baudm ,

I am trying to understand the model structure of VoxelNet and got stuck at the first layer...

![image](https://user-images.githubusercontent.com/42341018/62360387-f7a2e080-b518-11e9-98dd-f4c5803de3ab.png)

Could you explain a bit what the effect of this dense layer is? Usually these layers are used at the end of the structure for the classification task like this : 
![image](https://user-images.githubusercontent.com/42341018/62360576-6122ef00-b519-11e9-80d5-3d5043a75661.png)

 Why did you / the authors use that at the very beginning?

**Comment by baudm** [comment]
@xman236 thanks for your interest, but the authors of VoxelNet would be in a better position to answer your question.
